package com.servicerca.app.domain.model

data class User (val id: String,
                 val name1: String,
                 val name2: String?,
                 val lastname1: String,
                 val lastname2: String?,
                 val city: String,
                 val address: String,
                 val email: String,
                 val password: String,
                 val phoneNumber: String = "",
                 val profilePictureUrl: String = "",
                 val role: UserRole = UserRole.USER,
                 val completedServices: Int = 0,
                 val totalPoints: Int = 0,
                 val rating: Double = 0.0,
                 val memberSince: Int = 0,
                 val pendingReviews: Int = 0,
                 val approvedReviews: Int = 0,
                 val rejectReviews: Int = 0)
